/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(987c4b35-c426-4dd7-ad49-3c9fa4c65d20)]

/**
 * The XUL store is used to store information related to a XUL document/application.
 * Typically it is used to store the persisted state for the document, such as
 * window location, toolbars that are open and nodes that are open and closed in a tree.
 *
 * This XPCOM interface is no longer the way to access XULStore data.
 * To access XULStore data from JS, import XULStore.jsm; to access it from C++,
 * include XULStore.h.
 *
 * @note See toolkit/components/xulstore/src/lib.rs for the implementation
 * of this interface (and an explanation of its continued existence).
 */
interface nsIXULStore: nsISupports {};
